project_id = "tewkhjklgsedlooypkwo"

[functions.dentalink]
verify_jwt = false

[functions.mercadopago]
verify_jwt = false

[functions.whatsapp]
verify_jwt = false

[functions.funnel-lead]
verify_jwt = false

[functions.funnel-upload]
verify_jwt = false

[functions.funnel-ia-scan]
verify_jwt = false

[functions.funnel-checkout]
verify_jwt = false
